server:
  port: 8082
spring:
  application:
    name: LoginApi
  cloud:
    nacos:
      discovery:
        server-addr: 124.71.183.250:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080